name: Build Example
on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Platforms to build'
        type: choice
        default: 'macos'
        options:
          - 'macos'
          - 'windows'

jobs:
  macos:
    if: ${{ inputs.platform == 'macos' }}
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      - uses: bluefireteam/melos-action@v3
      - uses: goto-bus-stop/setup-zig@v2
      - uses: KyleMayes/install-llvm-action@v1
        with:
          version: "15"
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25b

      - name: Start iOS Simulator
        run: |
          DEVICE_ID=$(xcrun xctrace list devices | grep iPhone | head -1 | awk '{print $NF}' | tr -d '()')
          echo "DEVICE_ID=$DEVICE_ID" >> $GITHUB_ENV
          echo "DEVICE_ID=$DEVICE_ID"
          xcrun simctl boot $DEVICE_ID

      - name: Build all library binaries and place them
        run: |
          melos run build:apple
          melos run copylib:ios
          melos run copylib:macos

      - run: flutter config --enable-macos-desktop
      - run: flutter pub get
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true

  windows:
    if: ${{ inputs.platform == 'windows' }}
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          cache: true
      - run: flutter config --enable-macos-desktop
      - run: flutter pub get
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true