name: Create Release(s)

on:
  workflow_dispatch:
    inputs:
      version_parameters:
        description: 'Parameters to pass to "melos version"'
        required: true
        default: " "
        type: choice
        options:
          - "--"
          - "--prerelease"
          - "--graduate"

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
        # You will need to set a repository secret of BOT_ACCESS_TOKEN to your GitHub personal access token (PAT)
        # to allow for pushes to main from this Action.
          token: ${{ secrets.BOT_ACCESS_TOKEN }}
          fetch-depth: 0
      - name: Setup git
        run: |
          git config user.name "Kingkor Roy Tirtho"
          git config user.email "krtirtho@gmail.com"
      - uses: subosito/flutter-action@v2
      - uses: bluefireteam/melos-action@v3

      - name: Create the new version(s)
        run: melos version --yes ${{ inputs.version_parameters }}

      - name: Push created version commit
        run: git push
      - name: Push modified tags
        run: git push --tags